# -*- coding: utf-8 -*-
"""HelloStreamLit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g91afzvnJhX0Hyy090TKPJZ-acxlBDFq
"""

!pip install streamlit

import streamlit as st

st.title("Hello Streamlit World!")